# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'News' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

use_frameworks!

pod 'Alamofire'
pod 'Kingfisher'
pod 'PullToRefreshKit', '~> 0.4.0'
pod 'SwiftyJSON', :git => 'https://github.com/IBM-Swift/SwiftyJSON.git'

pod 'ChameleonFramework/Swift', :git=>'https://github.com/ViccAlexander/Chameleon.git'


end
